const courseSchedule =[
    {
      "code": "GSM 1002",
      "name": "02 Müzik II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Necla YAVUZ",
      "day": "PAZARTESİ",
      "time": "08:30-09:15",
      "room": "Müzik Odası"
    },
    {
      "code": "ATA 1002",
      "name": "02Atatürk İlk.ve İnk. Tarihi II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Ahmet GÜLEN",
      "day": "PAZARTESİ",
      "time": "13:00-13:45",
      "room": "D BLOK - D304 Laboratuvarı"
    },
    {
      "code": "ATA 1002",
      "name": "02Atatürk İlk.ve İnk. Tarihi II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Ahmet GÜLEN",
      "day": "PAZARTESİ",
      "time": "13:55-14:40",
      "room": "D BLOK - D304 Derslik"
    },
    {
      "code": "YBS 2016",
      "name": "Bilgisayar Ağları.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "PAZARTESİ",
      "time": "09:25-10:10",
      "room": "A Blok - A5 Derslik"
    },
    {
      "code": "YBS 2016",
      "name": "Bilgisayar Ağları.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "PAZARTESİ",
      "time": "10:20-11:05",
      "room": "A Blok - A5 Derslik"
    },
    {
      "code": "YBS 2016",
      "name": "Bilgisayar Ağları.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "PAZARTESİ",
      "time": "11:15-12:00",
      "room": "A Blok - A5 Derslik"
    },
    {
      "code": "YBS 3022",
      "name": "E-Ticaret ve E-iş.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "PAZARTESİ",
      "time": "09:25-10:10",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 3022",
      "name": "E-Ticaret ve E-iş.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "PAZARTESİ",
      "time": "10:20-11:05",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 3022",
      "name": "E-Ticaret ve E-iş.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "PAZARTESİ",
      "time": "11:15-12:00",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 4008",
      "name": "Kurumsal Kaynak Planlaması.",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "PAZARTESİ",
      "time": "13:00-13:45",
      "room": "E BLOK - E2 AMFİ "
    },
    {
      "code": "YBS 4008",
      "name": "Kurumsal Kaynak Planlaması.",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "PAZARTESİ",
      "time": "13:55-14:40",
      "room": "E BLOK - E2 AMFİ "
    },
    {
      "code": "YBS 4008",
      "name": "Kurumsal Kaynak Planlaması.",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "PAZARTESİ",
      "time": "14:50-15:35",
      "room": "E BLOK - E2 AMFİ "
    },
    {
      "code": "IBF 1006",
      "name": "Matematik II..",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Kaan YARALIOĞLU",
      "day": "PAZARTESİ",
      "time": "09:25-10:10",
      "room": "E BLOK - E2 AMFİ "
    },
    {
      "code": "IBF 1006",
      "name": "Matematik II..",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Kaan YARALIOĞLU",
      "day": "PAZARTESİ",
      "time": "10:20-11:05",
      "room": "E BLOK - E2 AMFİ "
    },
    {
      "code": "IBF 1006",
      "name": "Matematik II..",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Kaan YARALIOĞLU",
      "day": "PAZARTESİ",
      "time": "11:15-12:00",
      "room": "E BLOK - E2 AMFİ "
    },
    {
      "code": "YBS 3024",
      "name": "Mesleki Yabancı Dil II(Seç.).",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "PAZARTESİ",
      "time": "13:55-14:40",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 3024",
      "name": "Mesleki Yabancı Dil II(Seç.).",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "PAZARTESİ",
      "time": "14:50-15:35",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 2022",
      "name": "Web Tasarım Teknikleri.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PAZARTESİ",
      "time": "13:00-13:45",
      "room": "E Blok - E305 Laboratuvarı"
    },
    {
      "code": "YBS 2022",
      "name": "Web Tasarım Teknikleri.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PAZARTESİ",
      "time": "13:55-14:40",
      "room": "E Blok - E305 Laboratuvarı "
    },
    {
      "code": "YBS 2022",
      "name": "Web Tasarım Teknikleri.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PAZARTESİ",
      "time": "14:50-15:35",
      "room": "E Blok - E305 Laboratuvarı"
    },
    {
      "code": "YBS 2022",
      "name": "Web Tasarım Teknikleri.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PAZARTESİ",
      "time": "15:45-16:30",
      "room": "E Blok - E305 Laboratuvarı"
    },
    {
      "code": "YBS 4002",
      "name": "Yönetim Bilişim Sistemleri Semineri",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "PAZARTESİ",
      "time": "09:25-10:10",
      "room": "E BLOK - E1 Amfi"
    },
    {
      "code": "YBS 4002",
      "name": "Yönetim Bilişim Sistemleri Semineri",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "PAZARTESİ",
      "time": "10:20-11:05",
      "room": "E BLOK - E1 Amfi "
    },
    {
      "code": "YBS 4002",
      "name": "Yönetim Bilişim Sistemleri Semineri",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "PAZARTESİ",
      "time": "11:15-12:00",
      "room": "E BLOK - E1 Amfi "
    },
    {
      "code": "GSR 1002",
      "name": "02Resim II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Yeşim T ERCÜMENCİLER",
      "day": "SALI",
      "time": "08:30-09:15",
      "room": "Resim Odası"
    },
    {
      "code": "YBS 2014",
      "name": "Coğrafi Bilgi Sistemleri.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "SALI",
      "time": "09:25-10:10",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 2014",
      "name": "Coğrafi Bilgi Sistemleri.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "SALI",
      "time": "10:20-11:05",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 2014",
      "name": "Coğrafi Bilgi Sistemleri.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "SALI",
      "time": "11:15-12:00",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "IKT 1002",
      "name": "İktisada Giriş II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Aslı Seda KURT",
      "day": "SALI",
      "time": "09:25-10:10",
      "room": "E BLOK - E1 Amfi "
    },
    {
      "code": "IKT 1002",
      "name": "İktisada Giriş II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Aslı Seda KURT",
      "day": "SALI",
      "time": "10:20-11:05",
      "room": "E BLOK - E1 Amfi "
    },
    {
      "code": "IKT 1002",
      "name": "İktisada Giriş II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Aslı Seda KURT",
      "day": "SALI",
      "time": "11:15-12:00",
      "room": "E BLOK - E1 Amfi "
    },
    {
      "code": "YBS 4010",
      "name": "Kurumsal Bilgi Sistemleri.",
      "branch": "0",
      "year": 8,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "SALI",
      "time": "09:25-10:10",
      "room": "B Blok - B1 Derslik"
    },
    {
      "code": "YBS 4010",
      "name": "Kurumsal Bilgi Sistemleri.",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "SALI",
      "time": "10:20-11:05",
      "room": "B Blok - B1 Derslik"
    },
    {
      "code": "YBS 4010",
      "name": "Kurumsal Bilgi Sistemleri.",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "SALI",
      "time": "11:15-12:00",
      "room": "B Blok - B1 Derslik"
    },
    {
      "code": "YBS 4004",
      "name": "Sistem Güvenliği.",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Cem Yıldız",
      "day": "SALI",
      "time": "13:00-13:45",
      "room": "E Blok - E107 Laboratuvarı"
    },
    {
      "code": "YBS 4004",
      "name": "Sistem Güvenliği.",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Cem Yıldız",
      "day": "SALI",
      "time": "13:55-14:40",
      "room": "E Blok - E107 Laboratuvarı"
    },
    {
      "code": "YBS 4004",
      "name": "Sistem Güvenliği.",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Cem Yıldız",
      "day": "SALI",
      "time": "14:50-15:35",
      "room": "E Blok - E107 Laboratuvarı"
    },
    {
      "code": "YBS 2020",
      "name": "Veri Tabanı Yönetim Sistemlerine II.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "SALI",
      "time": "13:00-13:45",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 2020",
      "name": "Veri Tabanı Yönetim Sistemlerine II.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "SALI",
      "time": "13:55-14:40",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 2020",
      "name": "Veri Tabanı Yönetim Sistemlerine II.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Çiğdem TARHAN",
      "day": "SALI",
      "time": "14:50-15:35",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 1004",
      "name": "Yönetim Bilişim Sistemleri II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "SALI",
      "time": "13:00-13:45",
      "room": "E Blok - E1 Amfi"
    },
    {
      "code": "YBS 1004",
      "name": "Yönetim Bilişim Sistemleri II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "SALI",
      "time": "13:55-14:40",
      "room": "E Blok - E1 Amfi"
    },
    {
      "code": "YBS 1004",
      "name": "Yönetim Bilişim Sistemleri II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "SALI",
      "time": "14:50-15:35",
      "room": "E Blok - E1 Amfi"
    },
    {
      "code": "EMT3006",
      "name": "Yöneylem AraştırmasıII.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Kaan YARALIOĞLU",
      "day": "SALI",
      "time": "09:25-10:10",
      "room": "E BLOK - E2 AMFİ "
    },
    {
      "code": "EMT3006",
      "name": "Yöneylem AraştırmasıII.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Kaan YARALIOĞLU",
      "day": "SALI",
      "time": "10:20-11:05",
      "room": "E Blok - E2 Amfi "
    },
    {
      "code": "EMT3006",
      "name": "Yöneylem AraştırmasıII.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Kaan YARALIOĞLU",
      "day": "SALI",
      "time": "11:15-12:00",
      "room": "E Blok - E2 Amfi "
    },
    {
      "code": "YBS 1010",
      "name": "Bilgi ve İletişim Teknolojileri",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "ÇARŞAMBA",
      "time": "13:00-13:45",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 1010",
      "name": "Bilgi ve İletişim Teknolojileri",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "ÇARŞAMBA",
      "time": "13:55-14:40",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 1010",
      "name": "Bilgi ve İletişim Teknolojileri",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "ÇARŞAMBA",
      "time": "14:50-15:35",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 2018",
      "name": "Bulut Bilişim (Seç.).",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "ÇARŞAMBA",
      "time": "09:25-10:10",
      "room": "E Blok - E1 Amfi "
    },
    {
      "code": "YBS 2018",
      "name": "Bulut Bilişim (Seç.).",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "ÇARŞAMBA",
      "time": "10:20-11:05",
      "room": "E Blok - E1 Amfi "
    },
    {
      "code": "YBS 2018",
      "name": "Bulut Bilişim (Seç.).",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "ÇARŞAMBA",
      "time": "11:15-12:00",
      "room": "E Blok - E1 Amfi "
    },
    {
      "code": "YBS 3020",
      "name": "Coğrafi Bilgi Sistemlerinde Kurumsal Uygulamalar.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "ÇARŞAMBA",
      "time": "13:00-13:45",
      "room": "E Blok - E1 Amfi "
    },
    {
      "code": "YBS 3020",
      "name": "Coğrafi Bilgi Sistemlerinde Kurumsal Uygulamalar.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "ÇARŞAMBA",
      "time": "13:55-14:40",
      "room": "E Blok - E1 "
    },
    {
      "code": "YBS 3020",
      "name": "Coğrafi Bilgi Sistemlerinde Kurumsal Uygulamalar.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "ÇARŞAMBA",
      "time": "14:50-15:35",
      "room": "E Blok - E1 "
    },
    {
      "code": "YBS 4028",
      "name": "İçerik Yönetim Sistemleri (Seç.).",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "ÇARŞAMBA",
      "time": "08:30-09:15",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 4028",
      "name": "İçerik Yönetim Sistemleri (Seç.).",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "ÇARŞAMBA",
      "time": "09:25-10:10",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 4028",
      "name": "İçerik Yönetim Sistemleri (Seç.).",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "ÇARŞAMBA",
      "time": "10:20-11:05",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 4028",
      "name": "İçerik Yönetim Sistemleri (Seç.).",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Vahap TECİM",
      "day": "ÇARŞAMBA",
      "time": "11:15-12:00",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "IBF 1008",
      "name": "İstatistik II.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "İstem KÖYMEN",
      "day": "ÇARŞAMBA",
      "time": "13:00-13:45",
      "room": "E Blok - E2 AMFİ "
    },
    {
      "code": "IBF 1008",
      "name": "İstatistik II.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "İstem KÖYMEN",
      "day": "ÇARŞAMBA",
      "time": "13:55-14:40",
      "room": "E Blok - E2 AMFİ "
    },
    {
      "code": "IBF 1008",
      "name": "İstatistik II.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "İstem KÖYMEN",
      "day": "ÇARŞAMBA",
      "time": "14:50-15:35",
      "room": "E Blok - E2 AMFİ "
    },
    {
      "code": "YBS 1008",
      "name": "Programlama I",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Hakan AŞAN",
      "day": "ÇARŞAMBA",
      "time": "08:30-09:15",
      "room": "E Blok - E305 Laboratuvarı "
    },
    {
      "code": "YBS 1008",
      "name": "Programlama I",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Hakan AŞAN",
      "day": "ÇARŞAMBA",
      "time": "09:25-10:10",
      "room": "E BLOK - E305 Laboratuvarı "
    },
    {
      "code": "YBS 1008",
      "name": "Programlama I",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Hakan AŞAN",
      "day": "ÇARŞAMBA",
      "time": "10:20-11:05",
      "room": "E BLOK - E305 Laboratuvarı "
    },
    {
      "code": "YBS 1008",
      "name": "Programlama I",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Hakan AŞAN",
      "day": "ÇARŞAMBA",
      "time": "11:15-12:00",
      "room": "E BLOK - E305 Laboratuvarı "
    },
    {
      "code": "YBS 3028",
      "name": "Yönetişim ve E-Devlet.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "ÇARŞAMBA",
      "time": "09:25-10:10",
      "room": "E Blok - E2 AMFİ"
    },
    {
      "code": "YBS 3028",
      "name": "Yönetişim ve E-Devlet.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "ÇARŞAMBA",
      "time": "10:20-11:05",
      "room": "E Blok - E2 Amfi"
    },
    {
      "code": "YBS 3028",
      "name": "Yönetişim ve E-Devlet.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "ÇARŞAMBA",
      "time": "11:15-12:00",
      "room": "E Blok - E2 AMFİ"
    },
    {
      "code": "TDL 1002",
      "name": "02Türk Dili II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Rabia ERYILMAZ",
      "day": "PERŞEMBE",
      "time": "08:30-09:15",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "TDL 1002",
      "name": "02Türk Dili II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Rabia ERYILMAZ",
      "day": "PERŞEMBE",
      "time": "09:25-10:10",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YDİ 1008",
      "name": "1008Yabancı Dil II: İngilizce.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Gülay TÜRK",
      "day": "PERŞEMBE",
      "time": "10:20-11:05",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YDİ 1008",
      "name": "1008Yabancı Dil II: İngilizce.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Gülay TÜRK",
      "day": "PERŞEMBE",
      "time": "11:15-12:00",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YDİ 1008",
      "name": "1008Yabancı Dil II: İngilizce.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Gülay TÜRK",
      "day": "PERŞEMBE",
      "time": "13:00-13:45",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "YBS 2004",
      "name": "Bilgi Teknolojileri Proje Yönetimi.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "PERŞEMBE",
      "time": "09:25-10:10",
      "room": "E BLOK - E1 "
    },
    {
      "code": "YBS 2004",
      "name": "Bilgi Teknolojileri Proje Yönetimi.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "PERŞEMBE",
      "time": "10:20-11:05",
      "room": "E BLOK - E1 "
    },
    {
      "code": "YBS 2004",
      "name": "Bilgi Teknolojileri Proje Yönetimi.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Yılmaz GÖKŞEN",
      "day": "PERŞEMBE",
      "time": "11:15-12:00",
      "room": "E BLOK - E1 "
    },
    {
      "code": "ISL 1004",
      "name": "Finansal Muhasebe II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Nur GENÇYÜREK",
      "day": "PERŞEMBE",
      "time": "13:55-14:40",
      "room": "A7"
    },
    {
      "code": "ISL 1004",
      "name": "Finansal Muhasebe II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Nur GENÇYÜREK",
      "day": "PERŞEMBE",
      "time": "14:50-15:35",
      "room": "A7"
    },
    {
      "code": "ISL 1004",
      "name": "Finansal Muhasebe II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Nur GENÇYÜREK",
      "day": "PERŞEMBE",
      "time": "15:45-16:30",
      "room": "A7"
    },
    {
      "code": "YBS 4024",
      "name": "İş Zekası (Seç.).",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PERŞEMBE",
      "time": "09:25-10:10",
      "room": "E BLOK - E107 Laboratuvarı"
    },
    {
      "code": "YBS 4024",
      "name": "İş Zekası (Seç.).",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PERŞEMBE",
      "time": "10:20-11:05",
      "room": "E BLOK - E107 Laboratuvarı"
    },
    {
      "code": "YBS 4024",
      "name": "İş Zekası (Seç.).",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PERŞEMBE",
      "time": "11:15-12:00",
      "room": "E BLOK - E107 Laboratuvarı"
    },
    {
      "code": "ybs 4022",
      "name": "Mobil Uygulama Geliştirme",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Hakan AŞAN",
      "day": "PERŞEMBE",
      "time": "13:00-13:45",
      "room": "D107 (Lab)"
    },
    {
      "code": "ybs 4022",
      "name": "Mobil Uygulama Geliştirme",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Hakan AŞAN",
      "day": "PERŞEMBE",
      "time": "13:55-14:40",
      "room": "D107 (Lab)"
    },
    {
      "code": "ybs 4022",
      "name": "Mobil Uygulama Geliştirme",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Hakan AŞAN",
      "day": "PERŞEMBE",
      "time": "14:50-15:35",
      "room": "D107 (Lab)"
    },
    {
      "code": "ybs 4022",
      "name": "Mobil Uygulama Geliştirme",
      "branch": "0",
      "year": 4,
      "term": "bahar",
      "instructor": "Hakan AŞAN",
      "day": "PERŞEMBE",
      "time": "15:45-16:30",
      "room": "D107 (Lab)"
    },
    {
      "code": "YBS 3012",
      "name": "Uzaktan Algılama.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "PERŞEMBE",
      "time": "09:25-10:10",
      "room": "E BLOK - E305 LABORATUVARI "
    },
    {
      "code": "YBS 3012",
      "name": "Uzaktan Algılama.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "PERŞEMBE",
      "time": "10:20-11:05",
      "room": "E BLOK - E305 LABORATUVARI "
    },
    {
      "code": "YBS 3012",
      "name": "Uzaktan Algılama.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Kutan KORUYAN",
      "day": "PERŞEMBE",
      "time": "11:15-12:00",
      "room": "E BLOK - E305 LABORATUVARI "
    },
    {
      "code": "YBS 3018",
      "name": "Veri Madenciliği ve Bilgi Çıkarımı.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PERŞEMBE",
      "time": "13:00-13:45",
      "room": "E BLOK - E305 LABORATUVARI "
    },
    {
      "code": "YBS 3018",
      "name": "Veri Madenciliği ve Bilgi Çıkarımı.",
      "branch": "0",
      "year": 3,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PERŞEMBE",
      "time": "13:55-14:40",
      "room": "E BLOK - E305 LABORATUVARI "
    },
    {
      "code": "YBS 3018",
      "name": "Veri Madenciliği ve Bilgi Çıkarımı.",
      "branch": "0",
      "year": 6,
      "term": "bahar",
      "instructor": "Can AYDIN",
      "day": "PERŞEMBE",
      "time": "14:50-15:35",
      "room": "E BLOK - E305 LABORATUVARI "
    },
    {
      "code": "BDE 1002",
      "name": "02Beden Eğitimi II.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "İsmail AYDIN",
      "day": "CUMA",
      "time": "08:30-09:15",
      "room": "SporSalonu1"
    },
    {
      "code": "ISL 2014",
      "name": "Pazarlama.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Engin Yücel",
      "day": "CUMA",
      "time": "09:25-10:10",
      "room": "E BLOK - E1 "
    },
    {
      "code": "ISL 2014",
      "name": "Pazarlama.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Engin Yücel",
      "day": "CUMA",
      "time": "10:20-11:05",
      "room": "E BLOK - E1 "
    },
    {
      "code": "ISL 2014",
      "name": "Pazarlama.",
      "branch": "0",
      "year": 2,
      "term": "bahar",
      "instructor": "Engin Yücel",
      "day": "CUMA",
      "time": "11:15-12:00",
      "room": "E BLOK - E1 "
    },
    {
      "code": "EMT1004",
      "name": "Temel Bilgi Teknolojileri.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Efe SARIBAY",
      "day": "CUMA",
      "time": "09:25-10:10",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "EMT1004",
      "name": "Temel Bilgi Teknolojileri.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Efe SARIBAY",
      "day": "CUMA",
      "time": "10:20-11:05",
      "room": "Uzaktan Eğitim"
    },
    {
      "code": "EMT1004",
      "name": "Temel Bilgi Teknolojileri.",
      "branch": "0",
      "year": 1,
      "term": "bahar",
      "instructor": "Efe SARIBAY",
      "day": "CUMA",
      "time": "11:15-12:00",
      "room": "Uzaktan Eğitim"
    },
];

const academicTerms = [
  {
    name: "2024-2025 Güz",
    term: "guz",
    start: "30.09.2024",
    end: "17.01.2025",
    midterm: { start: "18.11.2024", end: "23.11.2024" },
    final: { start: "20.01.2025", end: "29.01.2025" },
    makeup: { start: "03.02.2025", end: "07.02.2025" }
  },
  {
    name: "2024-2025 Bahar",
    term: "bahar",
    start: "24.02.2025",
    end: "06.06.2025",
    midterm: { start: "14.04.2025", end: "21.04.2025" },
    final: { start: "23.06.2025", end: "02.07.2025" },
    makeup: { start: "07.07.2025", end: "11.07.2025" }
  }
];